M_LCDC_NDMARequestStatus EQU $0
M_LCDC_NDMARequestTxLen EQU $1
M_LCDC_NDMARequestSrc EQU $2
M_LCDC_NDMARequestSrcBank EQU $4
M_LCDC_NDMARequestDst EQU $5
M_LCDC_NDMARequestDstBank EQU $7

M_LCDC_NDMARequestSize EQU $8
M_LCDC_NDMARequestCount EQU $8

M_LCDC_NDMARequestStatusUndefined EQU $0
M_LCDC_NDMARequestStatusReady EQU $1
M_LCDC_NDMARequestStatusCompleted EQU $2

M_LCDC_NDMARequestProcessingCap EQU $180
M_LCDC_NDMARequestEmulatedProcessingCap EQU $16